name: orchidfestival
favicon: null
layout_spectrum: 0.23998934449627995
typography_spectrum: 0.2343518517445773
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2436512615531683
  lightness: 0.04579659318551421
  saturation: 0.8183148170355707
  rhythmicContrast: 0.057146153412759304
purpose: []
